services:
  backend:
    image: docker.io/nashsu/free_ask_internet:latest
    depends_on:
      - llm-freegpt35
    ports:
      - "40380:8000"
    restart: unless-stopped

  freeaskinternet-ui:
    image: docker.io/nashsu/free_ask_internet_ui:latest
    ports:
      - "40030:80"
    environment:
      BACKEND_HOST: "backend:40380"
    depends_on:
      - backend
    restart: unless-stopped

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    ports:
      - "40330:3000"
    environment:
      OPENAI_API_KEY: "FreeAskInternet"
      CODE: "martini" # 如果你想要设置页面的访问密码，请修改这里
      BASE_URL: "http://backend:40380"
      CUSTOM_MODELS: "-all,+gpt-3.5-turbo"
    depends_on:
      - llm-freegpt35
    restart: unless-stopped

  llm-freegpt35:
    image: missuo/freegpt35:latest
    restart: unless-stopped

  llm-kimi:
    image: vinlic/kimi-free-api:latest
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  llm-glm4:
    image: vinlic/glm-free-api:latest
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  llm-qwen:
    image: vinlic/qwen-free-api:latest
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'
    restart: unless-stopped
